spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:msql://localhost:3306/bs?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.z.Pojo
  mapper-locations: classpath:mapper/*.xml